spring:
  flyway:
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/UserDB
    username: postgres
    password: chanhhung96
    platform: postgres
  application:
    name: auth-service
server:
  port: 8083

