spring:
  flyway:
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/BookDB
    username: postgres
    password: chanhhung96
    platform: postgres
  application:
    name: book-service
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8082

