spring:
  application:
    name: BookAPIGateway
server:
  port: 9999
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    book-service:
      path: /bookAPI/**
      service-id: book-service
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'

